function cv = LGP(xtr,xte,yt,h,gb,covfunc,ypred)
vr = exp(2*h.lik);
xall = vertcat(xtr,xte);
yall = vertcat(yt,ypred);
L = pairwise(xall,yall);
kxx = feval(covfunc{:}, h.cov, xtr, xtr);
knx = feval(covfunc{:}, h.cov, xte, xtr);
knn = feval(covfunc{:}, h.cov, xte, xte);
kxn = knx';
kfx = feval(covfunc{:}, h.cov, xall, xtr);
kxf = kfx';
I = eye(size(kxx));
I = (vr)*I;
T = kxf*L*kfx;
V = (kxx+I)+((vr*gb)*(kxx\T));
cv = knn - (knx)*(V\kxn);
cv = diag(cv);
cv = max(cv,0);
cv = cv+vr;
